### ISSUE TITLE
As an art show staffer I want to be able to check in an artist at con

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#106]
This will pop up a view w/ a bunch of mostly-editable fields that are used to verify that all the data are correct at check-in time.

**Comment by Hugmonster** [comment]
This needs to be on the Artist Information Sheet,  we will be reviewing the information with the artists at show and then checking the artist in.  

The process of checking the artist in means that we have a signed artist/agent form on file, we have confirmed contact information and the piece information.   All pieces are hung.  Checking in the artist and Art should switch the art from the status of Hung from Expected.

**Comment by kitsuta** [comment]
Okay! Sounds like the key things that checking in an artist should do are:
- Locking all pieces down so the artist can't edit, add, or delete any (but the admin can)
- Locking the agent code so the artist cannot generate a new one (but the admin can, or at least can change the agent in case of an emergency)
- Locking down the art show application so that only admins can change information on it (this would mean any changes to, e.g, the room number would need to go through staff -- is that desired?)
- Changing any pieces that are Expected to Hung, as you described

It sounds like you want to use a paper form that the artist prints out to review the information, is that correct or would you want a form to pop up in the system where the admin can change the app information? Did you want both? Do you want this form to also display the pieces and their statuses, so the admin can change those during check-in, or should that be a separate page/form?

... Phew, sorry for the litany of questions.

**Comment by Hugmonster** [comment]
Locking all pieces down so the artist can't edit, add, or delete any (but the admin can)
Yes 

Locking the agent code so the artist cannot generate a new one (but the admin can, or at least can change the agent in case of an emergency)
Yes 

Locking down the art show application so that only admins can change information on it (this would mean any changes to, e.g, the room number would need to go through staff -- is that desired?) 
Yes
Changing any pieces that are Expected to Hung, as you described
Yes
It sounds like you want to use a paper form that the artist prints out to review the information, is that correct or would you want a form to pop up in the system where the admin can change the app information?    Paper form with us making corrections in system.  Will reprint for signature.

Did you want both?  YEs

Do you want this form to also display the pieces and their statuses, so the admin can change those during check-in, or should that be a separate page/form?   Yes I want the pieces and statuses

**Comment by Hugmonster** [comment]
Here is a mock up 
[Artist Check In Mock UP .xlsx](https://github.com/MidwestFurryFandom/art_show/files/2346429/Artist.Check.In.Mock.UP.xlsx)

**Comment by kitsuta** [comment]
Just to keep track of things here, we've discussed the exact form a little more and added the following details:
- the delivery method of art
- a space assignment box
- first/last name and legal name, since legal first and legal last name aren't actually columns so we can't edit them (and they're just guesses anyway)

**Comment by kitsuta** [comment]
We're also adding the piece's gallery to the piece table. Pieces in the General gallery should be first in the list.
