### ISSUE TITLE
As an artist who has been approved, I want to be able to submit a list of pieces that I will be showing

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#107]
From an email that links to this page, the artist will land at the page for their application's pieces.
From this page, there should be a button to add a piece. This will bring up a form to enter piece data. On this Add New Piece form, three buttons: Cancel, Save & Return to List, Save & Add Another Piece.

**Comment by Hugmonster** [comment]
Here are the fields I see in this page -   https://docs.google.com/spreadsheets/d/1N4uUTmudywkMjEGjMjE2mAytUJrjePQXjHSNj6Xpl3k/edit?usp=sharing  In the order I would like.  

I am also detailing the fields below in case that document will not open...

Artist ID  - <System Created>
Banner Name  - <ArtistApp>

Piece ID - <System Created>   Unique to the artist.  Artist ABC Can have peices 1 thru 20 and so can any one else.    We will use a combo of Artist ID and Piece ID in tha barcodes.

Piece Status - Admin Options: Expected, Received, Not Received, Hung, Removed, Voice Auction, Sold, Quick Sale, Return to Artist, Paid (On this screen it will stay Expected only option artists will have.  Art show staff and system changes will Move it thru the other choices.) 

For Sale? -  Drop Down:YES, NO

Piece Name - 50 Character Limit.  (Bid sheets will affect this) 

Piece Type - Drop Down:  Original, Print 
 
Gallery - Drop Down: General, Mature

Original Media -  15 Character Limit (Only Shows if piece is marked as an original. )

Print Media -  15 Character Limit (Only Shows if piece is marked as a print)

Print Number  - X (Being A Number that needs to be less than or equal to Print run but less than 1001.) (Only Shows if piece is marked as a print)

Of -  'OF'   Literally I just want that word between the two Print Number and Print Run (Only Shows if piece is marked as a print)

Print Run Y  - (Being A Number that Needs to be under 1001 but greater than or equal to print number (Only Shows if piece is marked as a print)

Opening Bid -  (Make N/A If for Sale is Marked NO )   Must be in whole dollars otherwise. )

Quick Sale Price -  (Make N/A If for Sale is Marked NO )   Must be in whole dollars otherwise 

**BUTTONS:** 
SAVE ( This saves the current items that have been entered, and triggers an email to the artist's email address.  The email will contain the list of all pieces currently on the list and a link to adjust said items.) 

I am Finished Print Form Button (Confirm pop-up, then print a item check form (with checkboxes) for use by art show staff at-con. Include signature line, and include agent signature line if agent exists.
( Ok so this button Should not exist to start, cannot exist till we make the form. )   
So should probably be on another ticket.

**Comment by kitsuta** [comment]
Specs look good! One minor thing -- IIRC, using a drop-down box for just two options is considered clunky for forms. I can instead show both options as a set of buttons where only one can be actively selected (but one must be selected before submitting the form).

**Comment by Hugmonster** [comment]
Sure that works as long as it works
 For you on the fields down the line.

Tricia

**Comment by kitsuta** [comment]
Ack, I know I asked earlier but I can't find if I wrote it down -- is "Banner Name" equivalent to "Artist Name" or is it a new field on the artist app?

**Comment by jmdawson** [comment]
A new field, but you might want to have a check for “same as my artist name.” I believe the intent is to capture what they want the top of their chunk of the art show to say.

**Comment by Hugmonster** [comment]
Correct it's the Banner I hang in the Bay
