### ISSUE TITLE
Selling Art Via Quick Sale 

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#122]
Will add more details need Ticket number for reference

**Comment by kitsuta** [comment]
From discussion: This is very similar to https://github.com/MidwestFurryFandom/art_show/issues/121, but needs to support people who do not have bidder numbers. We'll use their badge name to look them up, much like we do for signing up bidders (https://github.com/MidwestFurryFandom/art_show/issues/119) -- we basically just want to skip the step where we give them their bidder number and then enter their bidder number to make a sale.

System design wise, I think each piece we add to the sale should be saved BEFORE the sale is processed -- that way we can be super sure that two people aren't accidentally being checked out with the same piece ID (mostly this would happen due to typos). We can also show the piece name and info so the staffer can double-check they've got the right piece.

**Comment by Hugmonster** [comment]
Sounds good to me

Hugmonster
Art Show Director

**Comment by kitsuta** [comment]
Note to self that quick sales start before bidding is over, so there should definitely be a quicksale-optimized workflow available to staff.
