### ISSUE TITLE
Admin: Application Price not calculated on initial load of application details

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/art_show#19]
When initially loading an application's details, the application price is incorrectly displayed as "0." Saving the application, returning to the search, and reopening it refreshes the value to what it should be.

If an override value is entered before saving (including "0"), it will still override as normal.

Note that the "Art Show Cost" column on the search page does correctly show this value, even before saving and reloading.

**Comment by jmdawson** [comment]
That's a placeholder value being displayed, not an actual value in the field. It is a little confusing. I have no suggestion at this time what a better display is. Maybe... 'to be calculated' or something. It has this non-state because the application has not been approved, and thus has no _actual_ price. N/a might also work. It may also be appropriate on this page (the application view) to show the Art Show Price to make it clearer what is going on.

The "Art Show Cost" is a separate field that represents what it should cost, should it be approved.

**Comment by kitsuta** [comment]
Yeah, when I coded this I imagined the visual difference between placeholder text and real text to be much more than it is.

I'll remove the placeholder text and put a description _next to_ the box showing the app's potential cost (the number shown in the list view) and a note if there's no payment to be made yet.
