### ISSUE TITLE
Applicant's "edit" view will show 0 if allocated 'too many' spots

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#42]
If an admin increases an applicant's allocation to more than the number of spots an applicant can request (say from 4, the applicant max, to 6), the applicant's edit view will display this as 0 when they go to pay (having been approved).

**Comment by SkylerRingtail** [comment]
The new message is good, but if we display it we should hide the old message. Otherwise, we get the below redundancy:

Panels
An admin has granted you 5 panels. Please contact us via via Midwest FurFest Art Show <artshow@furfest.org> if you wish to change the number of panels on your application. [The new message that displays if > 4 panels/table sections]

You may contact us via Midwest FurFest Art Show <artshow@furfest.org> to request more than 4 panels. [The old message that normally displays]

**Comment by kitsuta** [comment]
.. Whoops.
