### ISSUE TITLE
Add controls to allow admin to mark application as paid

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#48]
In the other views (Dealers, attendee), we have a way to manually mark an attendee as paid and enter what it was they paid. We have no way to do that in art_show.

In the interim, I think I'll mark Amount_paid in the attendee as $X higher to account for this.

**Comment by kitsuta** [comment]
The art show application itself has no 'amount paid' attached to it since only people can pay us, not things. I guess the closest we can get to this would be to add the attendee's paid amount to the art show application..? Or just a button that adds the art show application's cost to the attendee's paid amount?

**Comment by jmdawson** [comment]
I have no idea right now. The issue came up because someone paid via paypal (not our normal) because 'Canada' and we have no way to record that, other than increasing their Amount Paid on the attendee page. It's not graceful.

**Comment by kitsuta** [comment]
We actually partly solved this with the `PAID` status for apps -- since admins can change apps' statuses, they can already mark them as 'paid' in that way. I'll add a way to record the actual payment as well.
